// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: api/demo/demo.proto

package demo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Demo service

type DemoService interface {
	Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Demo_StreamService, error)
	PingPong(ctx context.Context, opts ...client.CallOption) (Demo_PingPongService, error)
}

type demoService struct {
	c    client.Client
	name string
}

func NewDemoService(name string, c client.Client) DemoService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.demo"
	}
	return &demoService{
		c:    c,
		name: name,
	}
}

func (c *demoService) Call(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Demo.Call", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *demoService) Stream(ctx context.Context, in *StreamingRequest, opts ...client.CallOption) (Demo_StreamService, error) {
	req := c.c.NewRequest(c.name, "Demo.Stream", &StreamingRequest{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(in); err != nil {
		return nil, err
	}
	return &demoServiceStream{stream}, nil
}

type Demo_StreamService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Recv() (*StreamingResponse, error)
}

type demoServiceStream struct {
	stream client.Stream
}

func (x *demoServiceStream) Close() error {
	return x.stream.Close()
}

func (x *demoServiceStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *demoServiceStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *demoServiceStream) Recv() (*StreamingResponse, error) {
	m := new(StreamingResponse)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

func (c *demoService) PingPong(ctx context.Context, opts ...client.CallOption) (Demo_PingPongService, error) {
	req := c.c.NewRequest(c.name, "Demo.PingPong", &Ping{})
	stream, err := c.c.Stream(ctx, req, opts...)
	if err != nil {
		return nil, err
	}
	return &demoServicePingPong{stream}, nil
}

type Demo_PingPongService interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Ping) error
	Recv() (*Pong, error)
}

type demoServicePingPong struct {
	stream client.Stream
}

func (x *demoServicePingPong) Close() error {
	return x.stream.Close()
}

func (x *demoServicePingPong) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *demoServicePingPong) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *demoServicePingPong) Send(m *Ping) error {
	return x.stream.Send(m)
}

func (x *demoServicePingPong) Recv() (*Pong, error) {
	m := new(Pong)
	err := x.stream.Recv(m)
	if err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Demo service

type DemoHandler interface {
	Call(context.Context, *Request, *Response) error
	Stream(context.Context, *StreamingRequest, Demo_StreamStream) error
	PingPong(context.Context, Demo_PingPongStream) error
}

func RegisterDemoHandler(s server.Server, hdlr DemoHandler, opts ...server.HandlerOption) error {
	type demo interface {
		Call(ctx context.Context, in *Request, out *Response) error
		Stream(ctx context.Context, stream server.Stream) error
		PingPong(ctx context.Context, stream server.Stream) error
	}
	type Demo struct {
		demo
	}
	h := &demoHandler{hdlr}
	return s.Handle(s.NewHandler(&Demo{h}, opts...))
}

type demoHandler struct {
	DemoHandler
}

func (h *demoHandler) Call(ctx context.Context, in *Request, out *Response) error {
	return h.DemoHandler.Call(ctx, in, out)
}

func (h *demoHandler) Stream(ctx context.Context, stream server.Stream) error {
	m := new(StreamingRequest)
	if err := stream.Recv(m); err != nil {
		return err
	}
	return h.DemoHandler.Stream(ctx, m, &demoStreamStream{stream})
}

type Demo_StreamStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*StreamingResponse) error
}

type demoStreamStream struct {
	stream server.Stream
}

func (x *demoStreamStream) Close() error {
	return x.stream.Close()
}

func (x *demoStreamStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *demoStreamStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *demoStreamStream) Send(m *StreamingResponse) error {
	return x.stream.Send(m)
}

func (h *demoHandler) PingPong(ctx context.Context, stream server.Stream) error {
	return h.DemoHandler.PingPong(ctx, &demoPingPongStream{stream})
}

type Demo_PingPongStream interface {
	SendMsg(interface{}) error
	RecvMsg(interface{}) error
	Close() error
	Send(*Pong) error
	Recv() (*Ping, error)
}

type demoPingPongStream struct {
	stream server.Stream
}

func (x *demoPingPongStream) Close() error {
	return x.stream.Close()
}

func (x *demoPingPongStream) SendMsg(m interface{}) error {
	return x.stream.Send(m)
}

func (x *demoPingPongStream) RecvMsg(m interface{}) error {
	return x.stream.Recv(m)
}

func (x *demoPingPongStream) Send(m *Pong) error {
	return x.stream.Send(m)
}

func (x *demoPingPongStream) Recv() (*Ping, error) {
	m := new(Ping)
	if err := x.stream.Recv(m); err != nil {
		return nil, err
	}
	return m, nil
}
