// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/auth/auth.proto

package auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AdminInfo_Status int32

const (
	AdminInfo_NotExists    AdminInfo_Status = 0
	AdminInfo_Available    AdminInfo_Status = 1
	AdminInfo_NotAvailable AdminInfo_Status = 2
)

var AdminInfo_Status_name = map[int32]string{
	0: "NotExists",
	1: "Available",
	2: "NotAvailable",
}

var AdminInfo_Status_value = map[string]int32{
	"NotExists":    0,
	"Available":    1,
	"NotAvailable": 2,
}

func (x AdminInfo_Status) String() string {
	return proto.EnumName(AdminInfo_Status_name, int32(x))
}

func (AdminInfo_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_aa33bda803119f75, []int{4, 0}
}

type LoginReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa33bda803119f75, []int{0}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginReq) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa33bda803119f75, []int{1}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LoginRes struct {
	IsExist              bool     `protobuf:"varint,1,opt,name=isExist,proto3" json:"isExist,omitempty"`
	Available            bool     `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	Token                *Token   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRes) Reset()         { *m = LoginRes{} }
func (m *LoginRes) String() string { return proto.CompactTextString(m) }
func (*LoginRes) ProtoMessage()    {}
func (*LoginRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa33bda803119f75, []int{2}
}

func (m *LoginRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRes.Unmarshal(m, b)
}
func (m *LoginRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRes.Marshal(b, m, deterministic)
}
func (m *LoginRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRes.Merge(m, src)
}
func (m *LoginRes) XXX_Size() int {
	return xxx_messageInfo_LoginRes.Size(m)
}
func (m *LoginRes) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRes.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRes proto.InternalMessageInfo

func (m *LoginRes) GetIsExist() bool {
	if m != nil {
		return m.IsExist
	}
	return false
}

func (m *LoginRes) GetAvailable() bool {
	if m != nil {
		return m.Available
	}
	return false
}

func (m *LoginRes) GetToken() *Token {
	if m != nil {
		return m.Token
	}
	return nil
}

type OptResult struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OptResult) Reset()         { *m = OptResult{} }
func (m *OptResult) String() string { return proto.CompactTextString(m) }
func (*OptResult) ProtoMessage()    {}
func (*OptResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa33bda803119f75, []int{3}
}

func (m *OptResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OptResult.Unmarshal(m, b)
}
func (m *OptResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OptResult.Marshal(b, m, deterministic)
}
func (m *OptResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptResult.Merge(m, src)
}
func (m *OptResult) XXX_Size() int {
	return xxx_messageInfo_OptResult.Size(m)
}
func (m *OptResult) XXX_DiscardUnknown() {
	xxx_messageInfo_OptResult.DiscardUnknown(m)
}

var xxx_messageInfo_OptResult proto.InternalMessageInfo

func (m *OptResult) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type AdminInfo struct {
	Uid                  int64            `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar               string           `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	LastLoginTime        int64            `protobuf:"varint,4,opt,name=lastLoginTime,proto3" json:"lastLoginTime,omitempty"`
	RegisterTime         int64            `protobuf:"varint,5,opt,name=registerTime,proto3" json:"registerTime,omitempty"`
	Roles                []string         `protobuf:"bytes,6,rep,name=roles,proto3" json:"roles,omitempty"`
	Status               AdminInfo_Status `protobuf:"varint,7,opt,name=status,proto3,enum=auth.AdminInfo_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *AdminInfo) Reset()         { *m = AdminInfo{} }
func (m *AdminInfo) String() string { return proto.CompactTextString(m) }
func (*AdminInfo) ProtoMessage()    {}
func (*AdminInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_aa33bda803119f75, []int{4}
}

func (m *AdminInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminInfo.Unmarshal(m, b)
}
func (m *AdminInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminInfo.Marshal(b, m, deterministic)
}
func (m *AdminInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminInfo.Merge(m, src)
}
func (m *AdminInfo) XXX_Size() int {
	return xxx_messageInfo_AdminInfo.Size(m)
}
func (m *AdminInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AdminInfo proto.InternalMessageInfo

func (m *AdminInfo) GetUid() int64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *AdminInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AdminInfo) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *AdminInfo) GetLastLoginTime() int64 {
	if m != nil {
		return m.LastLoginTime
	}
	return 0
}

func (m *AdminInfo) GetRegisterTime() int64 {
	if m != nil {
		return m.RegisterTime
	}
	return 0
}

func (m *AdminInfo) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *AdminInfo) GetStatus() AdminInfo_Status {
	if m != nil {
		return m.Status
	}
	return AdminInfo_NotExists
}

func init() {
	proto.RegisterEnum("auth.AdminInfo_Status", AdminInfo_Status_name, AdminInfo_Status_value)
	proto.RegisterType((*LoginReq)(nil), "auth.LoginReq")
	proto.RegisterType((*Token)(nil), "auth.Token")
	proto.RegisterType((*LoginRes)(nil), "auth.LoginRes")
	proto.RegisterType((*OptResult)(nil), "auth.OptResult")
	proto.RegisterType((*AdminInfo)(nil), "auth.AdminInfo")
}

func init() { proto.RegisterFile("api/auth/auth.proto", fileDescriptor_aa33bda803119f75) }

var fileDescriptor_aa33bda803119f75 = []byte{
	// 397 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x5d, 0x8b, 0xd3, 0x40,
	0x14, 0xcd, 0xf7, 0x26, 0x77, 0x77, 0x6b, 0xb8, 0xca, 0x12, 0xaa, 0x42, 0x1c, 0x44, 0xe2, 0x4b,
	0x84, 0xfa, 0xe2, 0x6b, 0x05, 0x1f, 0x84, 0x65, 0x85, 0x71, 0xff, 0xc0, 0x94, 0x8e, 0xed, 0xd0,
	0x34, 0x13, 0x33, 0x93, 0xea, 0xbb, 0x3f, 0xc1, 0x3f, 0x2c, 0xb9, 0xf9, 0xa8, 0x85, 0x7d, 0x09,
	0xf7, 0xdc, 0x7b, 0x32, 0x67, 0xce, 0x99, 0x0b, 0xcf, 0x45, 0xa3, 0x3e, 0x88, 0xce, 0xee, 0xe9,
	0x53, 0x36, 0xad, 0xb6, 0x1a, 0x83, 0xbe, 0x66, 0x9f, 0x21, 0xbe, 0xd7, 0x3b, 0x55, 0x73, 0xf9,
	0x13, 0x97, 0x10, 0x77, 0x46, 0xb6, 0xb5, 0x38, 0xca, 0xcc, 0xcd, 0xdd, 0x22, 0xe1, 0x33, 0xee,
	0x67, 0x8d, 0x30, 0xe6, 0x97, 0x6e, 0xb7, 0x99, 0x37, 0xcc, 0x26, 0xcc, 0x5e, 0x43, 0xf8, 0xa8,
	0x0f, 0xb2, 0xc6, 0x17, 0x10, 0xda, 0xbe, 0x18, 0xff, 0x1e, 0x00, 0x93, 0xb3, 0x84, 0xc1, 0x0c,
	0xae, 0x94, 0xf9, 0xf2, 0x5b, 0x19, 0x4b, 0x9c, 0x98, 0x4f, 0x10, 0x5f, 0x41, 0x22, 0x4e, 0x42,
	0x55, 0x62, 0x53, 0x49, 0x52, 0x88, 0xf9, 0xb9, 0x81, 0x6f, 0xa6, 0x93, 0xfd, 0xdc, 0x2d, 0xae,
	0x57, 0xd7, 0x25, 0x19, 0x21, 0xd5, 0x49, 0xe6, 0x25, 0x24, 0xdf, 0x1a, 0xcb, 0xa5, 0xe9, 0x2a,
	0x8b, 0x0b, 0xf0, 0xf4, 0x61, 0x94, 0xf0, 0xf4, 0x81, 0xfd, 0xf5, 0x20, 0x59, 0x6f, 0x8f, 0xaa,
	0xfe, 0x5a, 0xff, 0xd0, 0x98, 0x82, 0xdf, 0xa9, 0x2d, 0x8d, 0x7d, 0xde, 0x97, 0x88, 0x10, 0x90,
	0xed, 0xc1, 0x1a, 0xd5, 0x78, 0x07, 0x91, 0x38, 0x09, 0x2b, 0x5a, 0x12, 0x4d, 0xf8, 0x88, 0xf0,
	0x2d, 0xdc, 0x56, 0xc2, 0x58, 0xf2, 0xf4, 0xa8, 0x8e, 0x32, 0x0b, 0xe8, 0x9c, 0xcb, 0x26, 0x32,
	0xb8, 0x69, 0xe5, 0x4e, 0x19, 0x2b, 0x5b, 0x22, 0x85, 0x44, 0xba, 0xe8, 0xf5, 0x79, 0xb5, 0xba,
	0x92, 0x26, 0x8b, 0x72, 0xbf, 0xcf, 0x8b, 0x00, 0x96, 0x10, 0x19, 0x2b, 0x6c, 0x67, 0xb2, 0xab,
	0xdc, 0x2d, 0x16, 0xab, 0xbb, 0xc1, 0xec, 0x7c, 0xfd, 0xf2, 0x3b, 0x4d, 0xf9, 0xc8, 0x62, 0x9f,
	0x20, 0x1a, 0x3a, 0x78, 0x0b, 0xc9, 0x83, 0xb6, 0x94, 0xa7, 0x49, 0x9d, 0x1e, 0xae, 0xa7, 0x04,
	0x53, 0x17, 0x53, 0xb8, 0x79, 0xd0, 0xf6, 0xdc, 0xf1, 0x56, 0x7f, 0x5c, 0x08, 0xd6, 0x9d, 0xdd,
	0xe3, 0x7b, 0x08, 0xe9, 0xe6, 0xb8, 0x18, 0xb4, 0xa6, 0x95, 0x58, 0x5e, 0x62, 0xc3, 0x1c, 0x2c,
	0x20, 0xba, 0xd7, 0x3b, 0xdd, 0x59, 0xfc, 0xff, 0x11, 0x96, 0xcf, 0x06, 0x30, 0xbf, 0x00, 0x73,
	0xf0, 0x1d, 0x04, 0x94, 0xf6, 0x53, 0xbc, 0xd9, 0x0c, 0x73, 0x36, 0x11, 0xed, 0xe3, 0xc7, 0x7f,
	0x01, 0x00, 0x00, 0xff, 0xff, 0x34, 0x09, 0x30, 0x0d, 0xa6, 0x02, 0x00, 0x00,
}
